services:
    abdev.qte:
        class: abdev\qte\qte
        arguments:
            - @request
            - @cache.driver
            - @config
            - @dbal.conn
            - @template
            - @user
            - @log
            - %core.root_path%
            - %core.php_ext%
            - %core.table_prefix%
    abdev.qte.main_listener:
        class: abdev\qte\event\main_listener
        arguments:
            - @request
            - @dbal.conn
            - @template
            - @user
            - @log
            - @abdev.qte
        tags:
            - { name: event.listener }
    abdev.qte.acp_listener:
        class: abdev\qte\event\acp_listener
        arguments:
            - @request
            - @dbal.conn
            - @user
            - @abdev.qte
            - %core.table_prefix%
        tags:
            - { name: event.listener }
